CREATE TABLE PRODUCTE (
	ID SMALLINT(4) NOT NULL PRIMARY KEY,
	DESCRIPCIO VARCHAR(50),
  	STOCKACTUAL TINYINT(3),
  	STOCKMINIM TINYINT(3),
  	PVP FLOAT(6,2)
 );
 
INSERT INTO PRODUCTE VALUES (1, 'Manaza', 10, 3, 10);
INSERT INTO PRODUCTE VALUES (2, 'Pera', 5, 2, 5);
INSERT INTO PRODUCTE VALUES (3, 'Coco', 8, 3, 20);
INSERT INTO PRODUCTE VALUES (4, 'Platano', 6, 2, 12);
INSERT INTO PRODUCTE VALUES (5, 'Fresa', 9, 4, 6);
INSERT INTO PRODUCTE VALUES (6, 'Melocoton', 10, 5, 9);

CREATE TABLE VENDES (
	ID SMALLINT(4) NOT NULL PRIMARY KEY,
  	IDPRODUCTE SMALLINT(4) NOT NULL REFERENCES producte(ID),
  	DATAVENDA DATE,
  	QUANTITAT TINYINT(3)
);

CREATE TABLE COMANDES (
	ID SMALLINT(4) NOT NULL PRIMARY KEY,
  	IDPRODUCTE SMALLINT(4) NOT NULL REFERENCES PRODUCTE(ID),
  	DATACOMANDA DATE,
  	QUANTITAT TINYINT(3)
);

