package entity;
// Generated 31-ene-2021 21:21:17 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

/**
 * Partida generated by hbm2java
 */
public class Partida  implements java.io.Serializable {


     private Integer idPartida;
     private Set movimiento = new HashSet(0);
     private Date created;
     private char guanyador;
     
    public Partida(char guanyador) {
        this.guanyador = guanyador;
    } 

    public Partida(Set movimiento, char guanyador) {
       this.movimiento = movimiento;
       this.guanyador = guanyador;
    }
   
    @Id
    @GeneratedValue
    @Column(name="id_partida")
    public Integer getIdPartida() {
        return this.idPartida;
    }
    
    public void setIdPartida(Integer idPartida) {
        this.idPartida = idPartida;
    }

    public Set getMovimiento() {
        return movimiento;
    }

    public void setMovimiento(Set movimiento) {
        this.movimiento = movimiento;
    }
    
    @Column(name="created")
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    
    @Column(name="guanyador")
    public char getGuanyador() {
        return this.guanyador;
    }
    
    public void setGuanyador(char guanyador) {
        this.guanyador = guanyador;
    }
}


